/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.inuoView.items {
	import laya.ui.*;
	import laya.display.*;

	public class CustomPicCellUI extends View {
		public var customName:Label;
		public var phoneNum:Label;
		public var btmLine:Image;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"View","props":{"width":300,"height":30},"compId":2,"child":[{"type":"Label","props":{"y":7,"x":5,"var":"customName","text":"贫富阳光主体公司","left":5,"fontSize":16,"font":"SimHei","color":"#0a0909"},"compId":3},{"type":"Label","props":{"y":7,"var":"phoneNum","text":"13567896989","right":5,"fontSize":16,"font":"SimHei","color":"#0a0909"},"compId":5},{"type":"Image","props":{"var":"btmLine","skin":"uiCommonUpdate/greenLine.png","right":0,"left":0,"bottom":0},"compId":6}],"loadList":["uiCommonUpdate/greenLine.png"],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}