/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.usercenter {
	import laya.ui.*;
	import laya.display.*;
	import laya.display.Text;
	import script.prefabScript.LinkTextControl;

	public class CustomerAddressItemUI extends View {
		public var conName:Label;
		public var phonetxt:Label;
		public var detailaddr:Label;
		public var btnDel:Text;
		public var defaultlbl:Label;
		public var defaultDelivery:Label;
		public var editTxt:Text;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"View","props":{"width":940,"height":80},"compId":2,"child":[{"type":"Image","props":{"y":0,"skin":"commers/cutline.png","right":0,"left":55,"bottom":0},"compId":17},{"type":"Label","props":{"y":28,"x":56,"width":197,"var":"conName","valign":"middle","text":"上海万能科技公司","height":24,"fontSize":24,"font":"SimHei","color":"#0","align":"center"},"compId":3},{"type":"Label","props":{"y":28,"x":259,"width":156,"var":"phonetxt","valign":"middle","text":"13564113173","height":24,"fontSize":24,"font":"SimHei","color":"#0","align":"left"},"compId":5},{"type":"Label","props":{"x":422,"wordWrap":true,"width":273,"var":"detailaddr","valign":"middle","top":0,"text":"上海市浦东新区周浦镇瑞浦路612弄23号1001室","height":80,"fontSize":20,"font":"SimHei","color":"#0","bottom":0,"align":"left"},"compId":6},{"type":"Text","props":{"y":32,"x":829,"var":"btnDel","text":"删除","presetID":1,"fontSize":16,"font":"SimHei","color":"#354052","isPresetRoot":true,"runtime":"laya.display.Text"},"compId":8,"child":[{"type":"Script","props":{"presetID":2,"runtime":"script.prefabScript.LinkTextControl"},"compId":9}]},{"type":"Label","props":{"y":10,"x":1,"width":52,"visible":false,"var":"defaultlbl","valign":"middle","text":"默认","height":32,"fontSize":18,"font":"SimHei","color":"#003dc6","borderColor":"#003dc6","bold":true,"align":"center"},"compId":19},{"type":"Label","props":{"y":28,"x":696,"width":126,"var":"defaultDelivery","valign":"middle","text":"工厂自提","height":24,"fontSize":20,"font":"SimHei","color":"#0","align":"center"},"compId":22},{"type":"Text","props":{"y":32,"x":883,"width":47,"visible":true,"var":"editTxt","text":"修改","presetID":1,"height":12,"fontSize":16,"font":"SimHei","color":"#354052","isPresetRoot":true,"runtime":"laya.display.Text"},"compId":24,"child":[{"type":"Script","props":{"presetID":2,"runtime":"script.prefabScript.LinkTextControl"},"compId":25}]}],"loadList":["commers/cutline.png","prefabs/LinksText.prefab"],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}