/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.usercenter {
	import laya.ui.*;
	import laya.display.*;
	import script.usercenter.CustomManagerController;
	import script.prefabScript.CmykInputControl;

	public class CustomManagerPanelUI extends View {
		public var addCustome:Button;
		public var customeList:List;
		public var searchInput:TextInput;
		public var searchBtn:Button;
		public var pageText:Label;
		public var prevPage:Button;
		public var nextPage:Button;
		public var addressPanel:Panel;
		public var customInfoBox:Box;
		public var customName:TextInput;
		public var delBtn:Button;
		public var customPhone:TextInput;
		public var delBtn:Button;
		public var confirmAddCustom:Button;
		public var closeAddBtn:Button;
		public var payType:ComboBox;
		public var businessMan:ComboBox;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("usercenter/CustomManagerPanel");

		}

	}
}