/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.usercenter {
	import laya.ui.*;
	import laya.display.*;
	import script.usercenter.OrderPriceSettingController;

	public class SellPriceSettingPanelUI extends View {
		public var mainpanel:Panel;
		public var orderSn:Label;
		public var orderoanel:Panel;
		public var orderbox:List;
		public var closebtn:Button;
		public var layoutCost:TextInput;
		public var designCost:TextInput;
		public var deliveryCost:TextInput;
		public var otherCost:TextInput;
		public var sellPrice:Label;
		public var okbtn:Button;
		public var moneyPaidlbl:Label;
		public var shareBtn:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("usercenter/SellPriceSettingPanel");

		}

	}
}