/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.usercenter {
	import laya.ui.*;
	import laya.display.*;

	public class WriteOffOrderItemUI extends View {
		public var orderid:Label;
		public var ordertime:Label;
		public var productnum:Label;
		public var sellPrice:Label;
		public var WriteoffMoney:Label;
		public var unWriteOffMoney:Label;
		public var selectBox:CheckBox;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"View","props":{"width":1600,"height":50},"compId":2,"child":[{"type":"Label","props":{"y":10,"x":157,"width":237,"var":"orderid","valign":"middle","text":"18014398509481987","height":29,"fontSize":24,"font":"SimHei","bold":true,"align":"left"},"compId":3},{"type":"Label","props":{"y":10,"x":443,"width":237,"var":"ordertime","valign":"middle","text":"2019-05-22 15:30:00","height":29,"fontSize":24,"font":"SimHei","bold":true,"align":"left"},"compId":4},{"type":"Label","props":{"y":10,"x":722,"width":60,"var":"productnum","valign":"middle","text":"1","height":29,"fontSize":24,"font":"SimHei","bold":true,"align":"center"},"compId":5},{"type":"Label","props":{"y":10,"x":849,"width":90,"var":"sellPrice","valign":"middle","text":"3495","height":29,"fontSize":24,"font":"SimHei","bold":true,"align":"center"},"compId":6},{"type":"Image","props":{"skin":"commers/cutline.png","right":0,"left":0,"height":1,"bottom":0},"compId":12},{"type":"Label","props":{"y":10,"x":1002,"width":85,"var":"WriteoffMoney","valign":"middle","text":"3495","height":29,"fontSize":24,"font":"SimHei","bold":true,"align":"center"},"compId":25},{"type":"Label","props":{"y":10,"x":1150,"width":85,"var":"unWriteOffMoney","valign":"middle","text":"3495","height":29,"fontSize":24,"font":"SimHei","bold":true,"align":"center"},"compId":26},{"type":"CheckBox","props":{"y":10,"x":34,"var":"selectBox","skin":"uiCommonUpdate/grennsel.png","scaleY":1.5,"scaleX":1.5},"compId":27}],"loadList":["commers/cutline.png","uiCommonUpdate/grennsel.png"],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}