/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.inuoView {
	import laya.ui.*;
	import laya.display.*;

	public class QrCodePanelUI extends View {
		public var closeBtn:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("inuoView/QrCodePanel");

		}

	}
}