/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.usercenter.items {
	import laya.ui.*;
	import laya.display.*;
	import laya.display.Text;
	import script.prefabScript.LinkTextControl;

	public class CustomeItemUI extends View {
		public var selectImg:Image;
		public var customName:Label;
		public var phoneNumber:Label;
		public var contactName:Label;
		public var updateInfoTxt:Text;
		public var deleteTxt:Text;
		public var addressTxt:Text;

		public static var uiView:Object =/*[STATIC SAFE]*/{"type":"View","props":{"width":500,"height":30},"compId":2,"child":[{"type":"Image","props":{"var":"selectImg","top":0,"skin":"commers/graydisable.jpg","right":0,"left":0,"bottom":0},"compId":13},{"type":"Label","props":{"y":7,"x":5,"width":161,"var":"customName","text":"客户名称最多六个字","height":14,"fontSize":14,"font":"SimHei","align":"center"},"compId":3},{"type":"Label","props":{"y":8,"x":175,"width":80,"var":"phoneNumber","text":"13899998888","height":14,"fontSize":14,"font":"SimHei"},"compId":4},{"type":"Label","props":{"y":8,"x":283,"width":80,"visible":false,"var":"contactName","text":"联系人名称","height":14,"fontSize":14,"font":"SimHei","align":"center"},"compId":5},{"type":"Text","props":{"y":7,"x":381,"var":"updateInfoTxt","text":"修改","presetID":1,"fontSize":14,"font":"SimHei","color":"#003dc6","bold":true,"isPresetRoot":true,"runtime":"laya.display.Text"},"compId":6,"child":[{"type":"Script","props":{"presetID":2,"runtime":"script.prefabScript.LinkTextControl"},"compId":8}]},{"type":"Text","props":{"y":7,"x":458,"var":"deleteTxt","text":"删除","presetID":1,"fontSize":14,"font":"SimHei","color":"#d92e16","bold":true,"isPresetRoot":true,"runtime":"laya.display.Text"},"compId":7,"child":[{"type":"Script","props":{"presetID":2,"runtime":"script.prefabScript.LinkTextControl"},"compId":9}]},{"type":"Text","props":{"y":7,"x":419,"var":"addressTxt","text":"地址","presetID":1,"fontSize":14,"font":"SimHei","color":"#003dc6","bold":true,"isPresetRoot":true,"runtime":"laya.display.Text"},"compId":10,"child":[{"type":"Script","props":{"presetID":2,"runtime":"script.prefabScript.LinkTextControl"},"compId":11}]},{"type":"Image","props":{"y":0,"skin":"commers/cutline.png","right":0,"left":0,"bottom":0},"compId":12}],"loadList":["commers/graydisable.jpg","prefabs/LinksText.prefab","commers/cutline.png"],"loadList3D":[]};
		override protected function createChildren():void {
			super.createChildren();
			createView(uiView);

		}

	}
}