/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.orderList {
	import laya.ui.*;
	import laya.display.*;
	import script.prefabScript.CustomListController;
	import script.prefabScript.CmykInputControl;
	import script.usercenter.CustomerTransactController;

	public class CustomerTransactionPanelUI extends View {
		public var ordertime:Label;
		public var orderBtn:Button;
		public var transactionBtn:Button;
		public var addChargeBtn:Button;
		public var balanceTxt:Label;
		public var paytype:RadioGroup;
		public var orderList:List;
		public var btnsearch:Button;
		public var totalSellMoney:Label;
		public var payMoney:Label;
		public var pagenum:Label;
		public var lastpage:Button;
		public var nextpage:Button;
		public var showCustomList:Button;
		public var curCustomName:TextInput;
		public var customListPanel:Panel;
		public var addChargePanel:Box;
		public var customerName:TextInput;
		public var delBtn:Button;
		public var transactionNum:TextInput;
		public var delBtn:Button;
		public var getMoney:TextInput;
		public var delBtn:Button;
		public var commentInput:TextInput;
		public var delBtn:Button;
		public var confirmAdd:Button;
		public var closeCharge:Button;
		public var channel:ComboBox;
		public var getmoneyDate:Label;
		public var writeoffBtn:Button;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("orderList/CustomerTransactionPanel");

		}

	}
}