/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.orderList {
	import laya.ui.*;
	import laya.display.*;
	import script.prefabScript.CustomListController;
	import script.usercenter.MyOrderControl;

	public class OrderListPanelUI extends View {
		public var ordertime:Label;
		public var orderBtn:Button;
		public var transactionBtn:Button;
		public var exportExcel:Button;
		public var paytype:RadioGroup;
		public var orderList:List;
		public var btnsearch:Button;
		public var ordertotalNum:Label;
		public var ordertotalMoney:Label;
		public var pagenum:Label;
		public var lastpage:Button;
		public var nextpage:Button;
		public var orderPlaceCombo:ComboBox;
		public var showCustomList:Button;
		public var curCustomName:TextInput;
		public var customListPanel:Panel;
		public var businessCombo:ComboBox;
		public var writeOffRadio:RadioGroup;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("orderList/OrderListPanel");

		}

	}
}