/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.orderList {
	import laya.ui.*;
	import laya.display.*;
	import script.prefabScript.CustomListController;
	import script.usercenter.StatisticalAnalyController;

	public class StatisticalAnalyPanelUI extends View {
		public var customerTab:Button;
		public var productTab:Button;
		public var areaTab:Button;
		public var orderBtn:Button;
		public var transactionBtn:Button;
		public var exportExcel:Button;
		public var btnsearch:Button;
		public var orderList:List;
		public var ordertotalNum:Label;
		public var ordertotalMoney:Label;
		public var pagenum:Label;
		public var lastpage:Button;
		public var nextpage:Button;
		public var customerQueryBox:Box;
		public var orderPlaceCombo:ComboBox;
		public var showCustomList:Button;
		public var curCustomName:TextInput;
		public var customListPanel:Panel;
		public var businessCombo:ComboBox;
		public var payTypeComBox:ComboBox;
		public var productQueryBox:Box;
		public var categoryComBox:ComboBox;
		public var rpoductComBoc:ComboBox;
		public var areaQueryBox:Box;
		public var btnSelArea:Button;
		public var areatxt:Label;
		public var btnSelCity:Button;
		public var citytxt:Label;
		public var btnSelProv:Button;
		public var province:Label;
		public var btnSelTown:Button;
		public var towntxt:Label;
		public var provbox:Image;
		public var provList:List;
		public var citybox:Image;
		public var cityList:List;
		public var townbox:Image;
		public var townList:List;
		public var areabox:Image;
		public var areaList:List;
		public var timeBox:Box;
		public var monthComBox:ComboBox;
		public var yearComBox:ComboBox;
		public var ordertime:Label;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("orderList/StatisticalAnalyPanel");

		}

	}
}